package com.bnu.springdemo.entity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "projectinformationsharingsystem")
public class Comment implements java.io.Serializable {

	private Integer commentId;
	private Project project;
	private String commentDescription;
	private Date commentDate;
	private Date commentTime;
	private int block;

	public Comment() {
	}

	public Comment(Project project, String commentDescription,
			Date commentDate, Date commentTime, int block) {
		this.project = project;
		this.commentDescription = commentDescription;
		this.commentDate = commentDate;
		this.commentTime = commentTime;
		this.block = block;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "comment_id", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "comment_description", nullable = false, length = 140)
	public String getCommentDescription() {
		return this.commentDescription;
	}

	public void setCommentDescription(String commentDescription) {
		this.commentDescription = commentDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "comment_date", nullable = false, length = 10)
	public Date getCommentDate() {
		return this.commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "comment_time", nullable = false, length = 8)
	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	@Column(name = "block", nullable = false)
	public int getBlock() {
		return this.block;
	}

	public void setBlock(int block) {
		this.block = block;
	}

}
