package com.bnu.springdemo.entity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domain generated by hbm2java
 */
@Entity
@Table(name = "domain", catalog = "projectinformationsharingsystem")
public class Domain implements java.io.Serializable {

	private Integer domainId;
	private String domainName;
	private int block;
	private Set<ProjectDomain> projectDomains = new HashSet<ProjectDomain>(0);

	public Domain() {
	}

	public Domain(String domainName, int block) {
		this.domainName = domainName;
		this.block = block;
	}

	public Domain(String domainName, int block,
			Set<ProjectDomain> projectDomains) {
		this.domainName = domainName;
		this.block = block;
		this.projectDomains = projectDomains;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "domain_id", unique = true, nullable = false)
	public Integer getDomainId() {
		return this.domainId;
	}

	public void setDomainId(Integer domainId) {
		this.domainId = domainId;
	}

	@Column(name = "domain_name", nullable = false, length = 45)
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	@Column(name = "block", nullable = false)
	public int getBlock() {
		return this.block;
	}

	public void setBlock(int block) {
		this.block = block;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domain")
	public Set<ProjectDomain> getProjectDomains() {
		return this.projectDomains;
	}

	public void setProjectDomains(Set<ProjectDomain> projectDomains) {
		this.projectDomains = projectDomains;
	}

}
