package com.bnu.springdemo.entity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Institute generated by hbm2java
 */
@Entity
@Table(name = "institute", catalog = "projectinformationsharingsystem")
public class Institute implements java.io.Serializable {

	private Long instituteId;
	private String instituteName;
	private int pending;
	private int block;
	private Set<UserIntitute> userIntitutes = new HashSet<UserIntitute>(0);
	private Set<InstituteAdmin> instituteAdmins = new HashSet<InstituteAdmin>(0);

	public Institute() {
	}

	public Institute(String instituteName, int pending, int block) {
		this.instituteName = instituteName;
		this.pending = pending;
		this.block = block;
	}

	public Institute(String instituteName, int pending, int block,
			Set<UserIntitute> userIntitutes, Set<InstituteAdmin> instituteAdmins) {
		this.instituteName = instituteName;
		this.pending = pending;
		this.block = block;
		this.userIntitutes = userIntitutes;
		this.instituteAdmins = instituteAdmins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "institute_id", unique = true, nullable = false)
	public Long getInstituteId() {
		return this.instituteId;
	}

	public void setInstituteId(Long instituteId) {
		this.instituteId = instituteId;
	}

	@Column(name = "institute_name", nullable = false, length = 60)
	public String getInstituteName() {
		return this.instituteName;
	}

	public void setInstituteName(String instituteName) {
		this.instituteName = instituteName;
	}

	@Column(name = "pending", nullable = false)
	public int getPending() {
		return this.pending;
	}

	public void setPending(int pending) {
		this.pending = pending;
	}

	@Column(name = "block", nullable = false)
	public int getBlock() {
		return this.block;
	}

	public void setBlock(int block) {
		this.block = block;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institute")
	public Set<UserIntitute> getUserIntitutes() {
		return this.userIntitutes;
	}

	public void setUserIntitutes(Set<UserIntitute> userIntitutes) {
		this.userIntitutes = userIntitutes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institute")
	public Set<InstituteAdmin> getInstituteAdmins() {
		return this.instituteAdmins;
	}

	public void setInstituteAdmins(Set<InstituteAdmin> instituteAdmins) {
		this.instituteAdmins = instituteAdmins;
	}

}
