package com.bnu.springdemo.entity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Keywords generated by hbm2java
 */
@Entity
@Table(name = "keywords", catalog = "projectinformationsharingsystem")
public class Keywords implements java.io.Serializable {

	private Integer keywordsId;
	private String keywordName;
	private int block;
	private Set<ProjectKeywords> projectKeywordses = new HashSet<ProjectKeywords>(
			0);

	public Keywords() {
	}

	public Keywords(String keywordName, int block) {
		this.keywordName = keywordName;
		this.block = block;
	}

	public Keywords(String keywordName, int block,
			Set<ProjectKeywords> projectKeywordses) {
		this.keywordName = keywordName;
		this.block = block;
		this.projectKeywordses = projectKeywordses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "keywords_id", unique = true, nullable = false)
	public Integer getKeywordsId() {
		return this.keywordsId;
	}

	public void setKeywordsId(Integer keywordsId) {
		this.keywordsId = keywordsId;
	}

	@Column(name = "keyword_name", nullable = false, length = 45)
	public String getKeywordName() {
		return this.keywordName;
	}

	public void setKeywordName(String keywordName) {
		this.keywordName = keywordName;
	}

	@Column(name = "block", nullable = false)
	public int getBlock() {
		return this.block;
	}

	public void setBlock(int block) {
		this.block = block;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "keywords")
	public Set<ProjectKeywords> getProjectKeywordses() {
		return this.projectKeywordses;
	}

	public void setProjectKeywordses(Set<ProjectKeywords> projectKeywordses) {
		this.projectKeywordses = projectKeywordses;
	}

}
