package com.bnu.springdemo.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectVisibility generated by hbm2java
 */
@Entity
@Table(name = "project_visibility", catalog = "projectinformationsharingsystem")
public class ProjectVisibility implements java.io.Serializable {

	private Long projectVisibilityId;
	private VisibilityLevel visibilityLevel;
	private Project project;

	public ProjectVisibility() {
	}

	public ProjectVisibility(VisibilityLevel visibilityLevel, Project project) {
		this.visibilityLevel = visibilityLevel;
		this.project = project;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_visibility_id", unique = true, nullable = false)
	public Long getProjectVisibilityId() {
		return this.projectVisibilityId;
	}

	public void setProjectVisibilityId(Long projectVisibilityId) {
		this.projectVisibilityId = projectVisibilityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "visibility_level_id", nullable = false)
	public VisibilityLevel getVisibilityLevel() {
		return this.visibilityLevel;
	}

	public void setVisibilityLevel(VisibilityLevel visibilityLevel) {
		this.visibilityLevel = visibilityLevel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
