package com.bnu.springdemo.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectDomain generated by hbm2java
 */
@Entity
@Table(name = "project_domain", catalog = "projectinformationsharingsystem")
public class ProjectDomain implements java.io.Serializable {

	private Long projectDomainId;
	private Project project;
	private Domain domain;

	public ProjectDomain() {
	}

	public ProjectDomain(Project project, Domain domain) {
		this.project = project;
		this.domain = domain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_domain_id", unique = true, nullable = false)
	public Long getProjectDomainId() {
		return this.projectDomainId;
	}

	public void setProjectDomainId(Long projectDomainId) {
		this.projectDomainId = projectDomainId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "domain_id", nullable = false)
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

}
