package com.bnu.springdemo.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectSharedWith generated by hbm2java
 */
@Entity
@Table(name = "project_shared_with", catalog = "projectinformationsharingsystem")
public class ProjectSharedWith implements java.io.Serializable {

	private Long projectSharedWithId;
	private Project project;

	public ProjectSharedWith() {
	}

	public ProjectSharedWith(Project project) {
		this.project = project;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_shared_with_id", unique = true, nullable = false)
	public Long getProjectSharedWithId() {
		return this.projectSharedWithId;
	}

	public void setProjectSharedWithId(Long projectSharedWithId) {
		this.projectSharedWithId = projectSharedWithId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
