package com.bnu.springdemo.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectToolsUsed generated by hbm2java
 */
@Entity
@Table(name = "project_tools_used", catalog = "projectinformationsharingsystem")
public class ProjectToolsUsed implements java.io.Serializable {

	private Long projectToolsUsedId;
	private ToolsAndTechnology toolsAndTechnology;
	private Project project;

	public ProjectToolsUsed() {
	}

	public ProjectToolsUsed(ToolsAndTechnology toolsAndTechnology,
			Project project) {
		this.toolsAndTechnology = toolsAndTechnology;
		this.project = project;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_tools_used_id", unique = true, nullable = false)
	public Long getProjectToolsUsedId() {
		return this.projectToolsUsedId;
	}

	public void setProjectToolsUsedId(Long projectToolsUsedId) {
		this.projectToolsUsedId = projectToolsUsedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tools_and_technology_id", nullable = false)
	public ToolsAndTechnology getToolsAndTechnology() {
		return this.toolsAndTechnology;
	}

	public void setToolsAndTechnology(ToolsAndTechnology toolsAndTechnology) {
		this.toolsAndTechnology = toolsAndTechnology;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
