package com.bnu.springdemo.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RatingByRole generated by hbm2java
 */
@Entity
@Table(name = "rating_by_role", catalog = "projectinformationsharingsystem")
public class RatingByRole implements java.io.Serializable {

	private Integer ratingByRoleId;
	private Project project;
	private ProjectRole projectRole;

	public RatingByRole() {
	}

	public RatingByRole(Project project, ProjectRole projectRole) {
		this.project = project;
		this.projectRole = projectRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rating_by_role_id", unique = true, nullable = false)
	public Integer getRatingByRoleId() {
		return this.ratingByRoleId;
	}

	public void setRatingByRoleId(Integer ratingByRoleId) {
		this.ratingByRoleId = ratingByRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_role_id", nullable = false)
	public ProjectRole getProjectRole() {
		return this.projectRole;
	}

	public void setProjectRole(ProjectRole projectRole) {
		this.projectRole = projectRole;
	}

}
