package com.bnu.springdemo.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RatingByUser generated by hbm2java
 */
@Entity
@Table(name = "rating_by_user", catalog = "projectinformationsharingsystem")
public class RatingByUser implements java.io.Serializable {

	private Integer ratingId;
	private Users users;
	private Project project;
	private long ratingPublic;

	public RatingByUser() {
	}

	public RatingByUser(Users users, Project project, long ratingPublic) {
		this.users = users;
		this.project = project;
		this.ratingPublic = ratingPublic;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rating_id", unique = true, nullable = false)
	public Integer getRatingId() {
		return this.ratingId;
	}

	public void setRatingId(Integer ratingId) {
		this.ratingId = ratingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "rating_public", nullable = false)
	public long getRatingPublic() {
		return this.ratingPublic;
	}

	public void setRatingPublic(long ratingPublic) {
		this.ratingPublic = ratingPublic;
	}

}
