package com.bnu.springdemo.entity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "projectinformationsharingsystem")
public class Role implements java.io.Serializable {

	private Integer roleId;
	private Set<ProjectRole> projectRoles = new HashSet<ProjectRole>(0);

	public Role() {
	}

	public Role(Set<ProjectRole> projectRoles) {
		this.projectRoles = projectRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<ProjectRole> getProjectRoles() {
		return this.projectRoles;
	}

	public void setProjectRoles(Set<ProjectRole> projectRoles) {
		this.projectRoles = projectRoles;
	}

}
