package com.bnu.springdemo.entity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ToolsAndTechnology generated by hbm2java
 */
@Entity
@Table(name = "tools_and_technology", catalog = "projectinformationsharingsystem")
public class ToolsAndTechnology implements java.io.Serializable {

	private Long toolsAndTechnologyId;
	private String toolsAndTechnologyName;
	private int block;
	private Set<ProjectToolsUsed> projectToolsUseds = new HashSet<ProjectToolsUsed>(
			0);

	public ToolsAndTechnology() {
	}

	public ToolsAndTechnology(String toolsAndTechnologyName, int block) {
		this.toolsAndTechnologyName = toolsAndTechnologyName;
		this.block = block;
	}

	public ToolsAndTechnology(String toolsAndTechnologyName, int block,
			Set<ProjectToolsUsed> projectToolsUseds) {
		this.toolsAndTechnologyName = toolsAndTechnologyName;
		this.block = block;
		this.projectToolsUseds = projectToolsUseds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tools_and_technology_id", unique = true, nullable = false)
	public Long getToolsAndTechnologyId() {
		return this.toolsAndTechnologyId;
	}

	public void setToolsAndTechnologyId(Long toolsAndTechnologyId) {
		this.toolsAndTechnologyId = toolsAndTechnologyId;
	}

	@Column(name = "tools_and_technology_name", nullable = false, length = 80)
	public String getToolsAndTechnologyName() {
		return this.toolsAndTechnologyName;
	}

	public void setToolsAndTechnologyName(String toolsAndTechnologyName) {
		this.toolsAndTechnologyName = toolsAndTechnologyName;
	}

	@Column(name = "block", nullable = false)
	public int getBlock() {
		return this.block;
	}

	public void setBlock(int block) {
		this.block = block;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "toolsAndTechnology")
	public Set<ProjectToolsUsed> getProjectToolsUseds() {
		return this.projectToolsUseds;
	}

	public void setProjectToolsUseds(Set<ProjectToolsUsed> projectToolsUseds) {
		this.projectToolsUseds = projectToolsUseds;
	}

}
